### ISSUE TITLE
Syntax Error/invalid syntax

### ISSUE THREAD

**Issue by Ppaja** [msieg/deep-visualizer#15]
Every time I try to get this run I get an Syntax Error. 
Im from germany and its so difficult to find a solution if you dont nativ speak english. 

I tried it with different versions of python, I tried it with google colab, I tried it with internet sites where you can run python. 
But every time Syntax Error/invalid syntax.

I tried with the whole code, with only one line each, with the linux lines (i have windows), tried the code from the read me but nothing works. Still syntax error.

Im new to AI and this things, so Im sure I make a mistake. But in the whole Internet I cant find one single video or article that explains exact what you have to do. Do I need anything else installed than python? Do I need another code? 

I hope somebody can help me. 
![3](https://user-images.githubusercontent.com/73185125/113971249-b825af00-9838-11eb-8402-73569f55330d.PNG)
![2](https://user-images.githubusercontent.com/73185125/113971252-b8be4580-9838-11eb-9e18-e8a325c739fd.PNG)
![1](https://user-images.githubusercontent.com/73185125/113971255-b8be4580-9838-11eb-9228-46dabc6d7746.PNG)

**Comment by gezquinndesign** [comment]
> open terminal and run these commands:

```
git clone https://github.com/msieg/deep-music-visualizer.git
cd deep-music-visualizer
pip install -r requirements.txt
```

These are commands you run from the terminal. In Windows you'll need to open up a [Console](https://devblogs.microsoft.com/commandline/windows-command-line-inside-the-windows-console/) and run the commands there rather than in the python shell.

Hope that helps you.

**Comment by hubortje** [comment]
Hallo, du musst zuerst Git installieren, um den Befehl git clone ausführen zu können.
https://gitforwindows.org/

Danach solltest du im Terminal bzw. der Powershell die Befehle ausführen können, du musst dazu nicht extra Python ausführen.


English translation:

Hello, you have to install git to run git clone.

Afterwards, you should be able to run the commands in the Terminal or Powershell, you don't have to run Python for this.

**Comment by msieg** [comment]
:)

**Comment by Ppaja** [comment]
> Hallo, du musst zuerst Git installieren, um den Befehl git clone ausführen zu können.
> https://gitforwindows.org/
> 
> Danach solltest du im Terminal bzw. der Powershell die Befehle ausführen können, du musst dazu nicht extra Python ausführen.
> 
> English translation:
> 
> Hello, you have to install git to run git clone.
> 
> Afterwards, you should be able to run the commands in the Terminal or Powershell, you don't have to run Python for this.

Danke funktioniert! :)
